export const BALANCE = {
  startCredits: 45000,
  startReputation: 40,
  refWeight: 170,
  weightPerPower: 22,
  guardCostPerPoint: 380,
  wagePerTrainDay: 90,
  repairCostPerDamage: 14,
  fuelEfficiencyBase: 1,
  maxTrainWagons: 8,
  securityCapPerCity: 4,
  destabilizationDelayDays: 4,
  emergencyThresholdDays: 5,
  warningThresholdDays: 9,
  freeplayThreatGrowth: 0.6,
  prestigeBonusShare: 0.02,
  loopResourcesPerWeek: { steel: 40, machinery: 12, fuel: 60 },
  trainNamePool: ['Ox', 'Ironsides', 'Comet', 'Dawn', 'Warden', 'Ember', 'Vanguard', 'Harbinger', 'Relic', 'Scout'],
}

export const SCORING = {
  profitPerPoint: 1 / 1200,
  revenuePerPoint: 1 / 8000,
  cityPerPoint: 3800,
  industryPerPoint: 1600,
  railwayPerPoint: 90,
  baseDestroyPerPoint: 9000,
  securityPerPoint: 1 / 140,
  contractPerPoint: 1500,
  failedPenalty: 4500,
  reliabilityBonus: 260000,
  loopCompletion: 520000,
  freeplayYearPerPoint: 52000,
  legacyMultiplier: 0.12,
}