import type {
  BuildKind,
  CityLevelDef,
  IndustryDef,
  LocomotiveDef,
  ReputationLevel,
  TechDef,
  TechId,
  WagonDef,
} from './types'

export const LOCOMOTIVES: Record<string, LocomotiveDef> = {
  'old-steam': {
    id: 'old-steam',
    name: 'Old Steam Engine',
    power: 6,
    speed: 45,
    fuelType: 'coal',
    fuelRate: 3.2,
    fuelCap: 3200,
    weight: 62,
    cost: 28000,
    maintenancePerDay: 90,
  },
  'diesel-hauler': {
    id: 'diesel-hauler',
    name: 'Diesel Hauler',
    power: 10,
    speed: 60,
    fuelType: 'diesel',
    fuelRate: 2.4,
    fuelCap: 2600,
    weight: 78,
    cost: 64000,
    maintenancePerDay: 130,
  },
  'express-diesel': {
    id: 'express-diesel',
    name: 'Express Diesel',
    power: 8,
    speed: 95,
    fuelType: 'diesel',
    fuelRate: 3.1,
    fuelCap: 2000,
    weight: 66,
    cost: 98000,
    maintenancePerDay: 170,
  },
  'heavy-electric': {
    id: 'heavy-electric',
    name: 'Heavy Electric',
    power: 14,
    speed: 75,
    fuelType: 'electric',
    fuelRate: 1.1,
    fuelCap: 4000,
    weight: 90,
    cost: 210000,
    maintenancePerDay: 120,
    techRequired: 'rail-reinforced',
  },
  'warlord-burner': {
    id: 'warlord-burner',
    name: 'Warlord Burner',
    power: 12,
    speed: 55,
    fuelType: 'coal',
    fuelRate: 4.2,
    fuelCap: 3400,
    weight: 104,
    cost: 155000,
    maintenancePerDay: 210,
    techRequired: 'loco-experimental',
  },
}

export const WAGONS: Record<string, WagonDef> = {
  'passenger-car': {
    id: 'passenger-car',
    name: 'Passenger Car',
    weight: 32,
    cargoCap: 0,
    passengerSeats: 60,
    fuelImpact: 1.05,
    riskMod: 1,
    armor: 0,
    cost: 16000,
    maintenancePerDay: 45,
  },
  boxcar: {
    id: 'boxcar',
    name: 'Boxcar',
    weight: 24,
    cargoCap: 42,
    passengerSeats: 0,
    fuelImpact: 1.0,
    riskMod: 1,
    armor: 0,
    cost: 9800,
    maintenancePerDay: 28,
  },
  flatbed: {
    id: 'flatbed',
    name: 'Flatbed',
    weight: 18,
    cargoCap: 50,
    passengerSeats: 0,
    fuelImpact: 1.0,
    riskMod: 1.05,
    armor: 0,
    cost: 8600,
    maintenancePerDay: 24,
  },
  tanker: {
    id: 'tanker',
    name: 'Tanker',
    weight: 28,
    cargoCap: 38,
    passengerSeats: 0,
    fuelImpact: 1.02,
    riskMod: 1.1,
    armor: 0,
    cost: 15000,
    maintenancePerDay: 34,
    allows: ['fuel', 'chemicals'],
    unlockContracts: 2,
  },
  reefer: {
    id: 'reefer',
    name: 'Refrigerated Car',
    weight: 34,
    cargoCap: 32,
    passengerSeats: 0,
    fuelImpact: 1.12,
    riskMod: 1,
    armor: 0,
    cost: 22000,
    maintenancePerDay: 40,
    allows: ['food', 'medicine', 'chemicals'],
    unlockContracts: 2,
  },
  'livestock-car': {
    id: 'livestock-car',
    name: 'Livestock Car',
    weight: 26,
    cargoCap: 28,
    passengerSeats: 0,
    fuelImpact: 1.04,
    riskMod: 1,
    armor: 0,
    cost: 12000,
    maintenancePerDay: 30,
    allows: ['food'],
    unlockContracts: 2,
  },
  'heavy-cargo': {
    id: 'heavy-cargo',
    name: 'Heavy Cargo Car',
    weight: 38,
    cargoCap: 60,
    passengerSeats: 0,
    fuelImpact: 1.06,
    riskMod: 1,
    armor: 0,
    cost: 20000,
    maintenancePerDay: 36,
    allows: ['ore', 'timber', 'steel', 'coal', 'machinery'],
    unlockContracts: 5,
  },
  'armored-car': {
    id: 'armored-car',
    name: 'Armored Car',
    weight: 42,
    cargoCap: 26,
    passengerSeats: 0,
    fuelImpact: 1.1,
    riskMod: 0.5,
    armor: 30,
    cost: 34000,
    maintenancePerDay: 55,
    unlockContracts: 5,
  },
  'fuel-wagon': {
    id: 'fuel-wagon',
    name: 'Fuel Wagon',
    weight: 40,
    cargoCap: 0,
    passengerSeats: 0,
    fuelImpact: 1.08,
    riskMod: 1.2,
    armor: 0,
    cost: 26000,
    maintenancePerDay: 30,
    fuelBonus: 14000,
    techRequired: 'fw-tank',
    unlockContracts: 8,
  },
}

export const CITY_LEVELS: CityLevelDef[] = [
  { level: 1, name: 'Settlement', requiresInfluence: 0, unlockedBuilds: ['housing', 'watchtower', 'warehouse', 'station-platform'], unlockedIndustries: [] },
  { level: 2, name: 'Town', requiresInfluence: 25, unlockedBuilds: ['mine', 'agriculture', 'repair-depot', 'patrol-station', 'food-distribution'], unlockedIndustries: ['sawmill'] },
  { level: 3, name: 'Industrial City', requiresInfluence: 50, unlockedBuilds: ['refinery', 'factory', 'fuel-station', 'security-depot', 'hospital'], unlockedIndustries: ['steel-mill', 'refinery', 'machine-factory'] },
  { level: 4, name: 'Major Hub', requiresInfluence: 70, unlockedBuilds: ['rail-yard', 'cargo-terminal', 'military-base', 'water-treatment', 'automated-loading'], unlockedIndustries: ['chemical-plant', 'weapon-factory'] },
  { level: 5, name: 'Metropolitan Hub', requiresInfluence: 90, unlockedBuilds: ['heating', 'maintenance-shed'], unlockedIndustries: ['metropolitan'] },
]

export const INDUSTRIES: Record<string, IndustryDef> = {
  sawmill: {
    kind: 'sawmill',
    name: 'Sawmill',
    levelRequired: 2,
    produces: 'timber',
    producesPerDay: 22,
    inputs: {},
    buildCost: 18000,
    buildTimeDays: 10,
  },
  mine: {
    kind: 'mine',
    name: 'Mine',
    levelRequired: 2,
    produces: 'ore',
    producesPerDay: 30,
    inputs: { fuel: 4 },
    buildCost: 24000,
    buildTimeDays: 14,
  },
  refinery: {
    kind: 'refinery',
    name: 'Refinery',
    levelRequired: 3,
    produces: 'fuel',
    producesPerDay: 26,
    inputs: { ore: 10 },
    buildCost: 56000,
    buildTimeDays: 22,
  },
  'steel-mill': {
    kind: 'steel-mill',
    name: 'Steel Mill',
    levelRequired: 3,
    produces: 'steel',
    producesPerDay: 24,
    inputs: { ore: 18, coal: 12 },
    buildCost: 84000,
    buildTimeDays: 28,
  },
  'machine-factory': {
    kind: 'machine-factory',
    name: 'Machine Factory',
    levelRequired: 3,
    produces: 'machinery',
    producesPerDay: 9,
    inputs: { steel: 6, fuel: 3 },
    buildCost: 110000,
    buildTimeDays: 32,
  },
  'chemical-plant': {
    kind: 'chemical-plant',
    name: 'Chemical Plant',
    levelRequired: 4,
    produces: 'chemicals',
    producesPerDay: 12,
    inputs: { coal: 8, steel: 3 },
    buildCost: 150000,
    buildTimeDays: 40,
  },
  agriculture: {
    kind: 'agriculture',
    name: 'Agricultural Complex',
    levelRequired: 2,
    produces: 'food',
    producesPerDay: 34,
    inputs: { fuel: 2 },
    buildCost: 22000,
    buildTimeDays: 12,
  },
  hospital: {
    kind: 'hospital',
    name: 'Hospital',
    levelRequired: 3,
    produces: 'medicine',
    producesPerDay: 6,
    inputs: { chemicals: 2 },
    buildCost: 60000,
    buildTimeDays: 24,
  },
}

export const BUILDS: Record<BuildKind, { name: string; description: string; cost: number; influence: number; effects: string }> = {
  watchtower: { name: 'Watchtower', description: 'A watchtower that detects bandits early along nearby lines.', cost: 12000, influence: 5, effects: 'reduces threat on routes through this city' },
  'patrol-station': { name: 'Patrol Station', description: 'Armed patrols guard the immediate rail approaches.', cost: 38000, influence: 10, effects: 'reduces threat, protects against track sabotage' },
  'security-depot': { name: 'Security Depot', description: 'A depot that can respond fast to any breach on the network.', cost: 92000, influence: 15, effects: 'large threat reduction and anti-sabotage' },
  'military-base': { name: 'Military Railway Base', description: 'A fortified base that can project security across a region.', cost: 240000, influence: 30, effects: 'major threat reduction, unlocks anti-bandit operations' },
  'repair-depot': { name: 'Repair Depot', description: 'Local repairs so broken trains return to service faster.', cost: 18000, influence: 6, effects: 'reduces maintenance time' },
  'fuel-station': { name: 'Fuel Station', description: 'Guaranteed fuel supply for trains refueling here.', cost: 32000, influence: 8, effects: 'reduces fuel costs for routes through this city' },
  'cargo-terminal': { name: 'Cargo Terminal', description: 'Bigger payloads move through this station.', cost: 68000, influence: 14, effects: 'increases contract volume and storage' },
  'automated-loading': { name: 'Automated Loading', description: 'Robotic loaders speed turnarounds.', cost: 120000, influence: 20, effects: 'faster contract turnaround' },
  hospital: { name: 'Hospital', description: 'A working hospital for the city and its passengers.', cost: 55000, influence: 12, effects: 'produces medicine, raises population' },
  housing: { name: 'Housing', description: 'New homes for the growing population.', cost: 26000, influence: 8, effects: 'raises population growth' },
  'food-distribution': { name: 'Food Distribution', description: 'Evenly fed population, less waste.', cost: 15000, influence: 5, effects: 'reduces food consumption' },
  'water-treatment': { name: 'Water Treatment', description: 'Clean water for the city.', cost: 45000, influence: 10, effects: 'raises population growth' },
  heating: { name: 'Heating Plant', description: 'Heat in winter for a whole district.', cost: 90000, influence: 15, effects: 'reduces winter fuel demand' },
  mine: { name: 'Mine (Industry)', description: 'A new extraction mine.', cost: 24000, influence: 8, effects: 'produces ore' },
  refinery: { name: 'Refinery (Industry)', description: 'Process ore into fuel.', cost: 56000, influence: 12, effects: 'produces fuel' },
  factory: { name: 'Factory (Industry)', description: 'Restore a shattered factory.', cost: 85000, influence: 18, effects: 'produces machinery' },
  agriculture: { name: 'Agriculture (Industry)', description: 'Greenhouses and farms.', cost: 22000, influence: 7, effects: 'produces food' },
  warehouse: { name: 'Warehouse', description: 'More storage for spare goods.', cost: 13000, influence: 4, effects: 'raises storage capacity' },
  'station-platform': { name: 'Station Platform', description: 'Another platform means more trains.', cost: 16000, influence: 5, effects: 'raises railway level' },
  'rail-yard': { name: 'Rail Yard', description: 'A marshalling yard to route traffic.', cost: 70000, influence: 15, effects: 'raises railway level, better contracts' },
  'maintenance-shed': { name: 'Maintenance Shed', description: 'Overnight servicing for the whole fleet.', cost: 88000, influence: 16, effects: 'reduces fleet maintenance cost' },
}

export const REPUTATION_ORDER: ReputationLevel[] = [
  'hostile',
  'suspicious',
  'neutral',
  'cooperative',
  'friendly',
  'allied',
  'strategic-partner',
]

export const REPUTATION_SCORE: Record<ReputationLevel, number> = {
  hostile: -40,
  suspicious: -10,
  neutral: 0,
  cooperative: 20,
  friendly: 45,
  allied: 75,
  'strategic-partner': 110,
}

export const TECH: Record<TechId, TechDef> = {
  'fw-lightweight': {
    id: 'fw-lightweight',
    name: 'Lightweight Materials',
    category: 'wagons',
    description: 'Wagon structures shave weight without losing capacity.',
    cost: 30000,
    timeDays: 12,
    perk: { speedBonus: 0.08, capacityBonus: 0.05 },
  },
  'fw-high-capacity': {
    id: 'fw-high-capacity',
    name: 'High-Capacity Freight',
    category: 'wagons',
    description: 'Bigger bays fit more freight per wagon.',
    cost: 52000,
    timeDays: 16,
    perk: { capacityBonus: 0.15 },
    requires: ['fw-lightweight'],
  },
  'fw-reefer': {
    id: 'fw-reefer',
    name: 'Refrigerated Cargo',
    category: 'wagons',
    description: 'Cold chain for food and medicine across the wasteland.',
    cost: 64000,
    timeDays: 18,
    perk: { fuelEfficiency: 0.04 },
    requires: ['fw-lightweight'],
  },
  'fw-passenger': {
    id: 'fw-passenger',
    name: 'Advanced Passenger Cars',
    category: 'wagons',
    description: 'Comfortable, fast passenger stock people will pay for.',
    cost: 90000,
    timeDays: 22,
    perk: { reputationRate: 0.2, speedBonus: 0.03 },
  },
  'fw-tank': {
    id: 'fw-tank',
    name: 'Heavy Fuel Systems',
    category: 'wagons',
    description: 'Fuel wagons that stretch a fleet\u2019s legs.',
    cost: 48000,
    timeDays: 15,
    perk: { rangeBonus: 0.15 },
  },
  'loco-power': {
    id: 'loco-power',
    name: 'Reconditioned Engines',
    category: 'locomotives',
    description: 'Overhauls that pull more up the grades.',
    cost: 60000,
    timeDays: 14,
    perk: { powerBonus: 0.12 },
  },
  'loco-speed': {
    id: 'loco-speed',
    name: 'High-Speed Drive',
    category: 'locomotives',
    description: 'Gearing that cuts journey times.',
    cost: 86000,
    timeDays: 20,
    perk: { speedBonus: 0.15 },
  },
  'loco-fuel': {
    id: 'loco-fuel',
    name: 'Efficient Combustion',
    category: 'locomotives',
    description: 'More distance per tank of fuel.',
    cost: 110000,
    timeDays: 24,
    perk: { fuelEfficiency: 0.18 },
  },
  'loco-range': {
    id: 'loco-range',
    name: 'Extended Range',
    category: 'locomotives',
    description: 'Larger tenders let trains skip the fuel stops.',
    cost: 50000,
    timeDays: 14,
    perk: { rangeBonus: 0.2 },
  },
  'loco-experimental': {
    id: 'loco-experimental',
    name: 'Experimental Power Cell',
    category: 'locomotives',
    description: 'Unlocks the Warlord Burner project locomotive.',
    cost: 220000,
    timeDays: 40,
    perk: { powerBonus: 0.25, fuelEfficiency: 0.1 },
  },
  'rail-reinforced': {
    id: 'rail-reinforced',
    name: 'Reinforced Track',
    category: 'railway',
    description: 'Track that takes heavier trains and barely wears.',
    cost: 74000,
    timeDays: 18,
    perk: { maintenanceReduction: 0.15, capacityBonus: 0.08 },
  },
  'rail-highspeed': {
    id: 'rail-highspeed',
    name: 'High-Speed Rails',
    category: 'railway',
    description: 'Smooth rail and banking for the express network.',
    cost: 160000,
    timeDays: 30,
    perk: { speedBonus: 0.2 },
    requires: ['rail-reinforced'],
  },
  'rail-quickrepair': {
    id: 'rail-quickrepair',
    name: 'Mobile Repair Teams',
    category: 'railway',
    description: 'Track troops that patch breaks overnight.',
    cost: 42000,
    timeDays: 12,
    perk: { maintenanceReduction: 0.2 },
  },
  'rail-comms': {
    id: 'rail-comms',
    name: 'Railway Communications',
    category: 'railway',
    description: 'Signal wires that turn a line into a nervous system.',
    cost: 58000,
    timeDays: 16,
    perk: { threatReduction: 0.1, speedBonus: 0.04 },
  },
  'sec-armored-wagon': {
    id: 'sec-armored-wagon',
    name: 'Armored Wagon Upgrade',
    category: 'security',
    description: 'Plate the fleet against raiders.',
    cost: 70000,
    timeDays: 16,
    perk: { securityBonus: 0.15 },
  },
  'sec-defense': {
    id: 'sec-defense',
    name: 'Defensive Systems',
    category: 'security',
    description: 'Countermeasures for ambushes.',
    cost: 96000,
    timeDays: 20,
    perk: { securityBonus: 0.25 },
  },
  'sec-teams': {
    id: 'sec-teams',
    name: 'Security Teams',
    category: 'security',
    description: 'Trained guards that ride the prizes.',
    cost: 48000,
    timeDays: 12,
    perk: { threatReduction: 0.15 },
  },
  'sec-earlywarning': {
    id: 'sec-earlywarning',
    name: 'Early Warning',
    category: 'security',
    description: 'Scouts that report movement far up the line.',
    cost: 86000,
    timeDays: 18,
    perk: { threatReduction: 0.15, speedBonus: 0.02 },
  },
  'sec-escort': {
    id: 'sec-escort',
    name: 'Escort Trains',
    category: 'security',
    description: 'Armed railcars that shadow convoys.',
    cost: 140000,
    timeDays: 26,
    perk: { securityBonus: 0.3 },
    requires: ['sec-defense'],
  },
}

export const ACHIEVEMENTS: Record<string, { name: string; description: string }> = {
  'first-journey': { name: 'First Journey', description: 'Complete your first contract.' },
  'iron-road': { name: 'Iron Road', description: 'Transport 1,000 tons of cargo.' },
  'people-mover': { name: 'People Mover', description: 'Transport 1,000 passengers.' },
  industrialist: { name: 'Industrialist', description: 'Restore your first factory.' },
  'safe-passage': { name: 'Safe Passage', description: 'Survive 10 bandit encounters.' },
  'regional-power': { name: 'Regional Power', description: 'Connect 10 cities.' },
  'civilization-builder': { name: 'Civilization Builder', description: 'Reach 1,000,000 population supported.' },
  'the-great-loop': { name: 'The Great Loop', description: 'Complete the endgame loop.' },
  'second-chance': { name: 'Second Chance', description: 'Prestige for the first time.' },
  'eternal-rail': { name: 'Eternal Rail', description: 'Reach Freeplay Year 20.' },
}