import type { CityDef, RegionDef, SegmentDef, WorldConfig } from './types'

export const REGIONS: Record<string, RegionDef> = {
  central: { id: 'central', name: 'Central Reclamation', banditBaseThreat: 0.16, banditConfederation: false },
  northern: { id: 'northern', name: 'Northern Wasteland', banditBaseThreat: 0.34, banditConfederation: true },
  eastern: { id: 'eastern', name: 'Eastern Rail Union', banditBaseThreat: 0.1, banditConfederation: false },
  southern: { id: 'southern', name: 'Southern Old Fields', banditBaseThreat: 0.2, banditConfederation: false },
}

export const CITIES: CityDef[] = [
  {
    id: 'new-lyon',
    name: 'New Lyon',
    region: 'central',
    level: 3,
    population: 42000,
    x: 42,
    y: 34,
    produces: ['steel', 'machinery'],
    needs: ['food', 'medicine', 'fuel'],
    industries: ['steel-mill', 'machine-factory'],
    consumePerDay: { food: 34, medicine: 2.5, fuel: 18 },
    storageCap: { food: 400, medicine: 40, fuel: 260, ore: 300, steel: 300, coal: 220, machinery: 120 },
    influence: 30,
    securityLevel: 1,
    reputation: 'friendly',
  },
  {
    id: 'paris-valo',
    name: 'Paris-Valo',
    region: 'central',
    level: 4,
    population: 88000,
    x: 64,
    y: 22,
    produces: ['goods', 'chemicals'],
    needs: ['food', 'fuel', 'medicine', 'machinery'],
    industries: ['chemical-plant'],
    consumePerDay: { food: 70, medicine: 5, fuel: 34, machinery: 4 },
    storageCap: { food: 620, medicine: 70, fuel: 360, chemicals: 200, goods: 400, steel: 200 },
    influence: 55,
    securityLevel: 2,
    reputation: 'cooperative',
  },
  {
    id: 'bordeaux-est',
    name: 'Bordeaux-Est',
    region: 'central',
    level: 2,
    population: 12000,
    x: 22,
    y: 42,
    produces: ['timber'],
    needs: ['fuel', 'medicine', 'food'],
    industries: ['sawmill'],
    consumePerDay: { food: 10, medicine: 0.8, fuel: 6 },
    storageCap: { food: 120, medicine: 12, fuel: 80, timber: 200 },
    influence: 12,
    securityLevel: 1,
    reputation: 'neutral',
  },
  {
    id: 'rouen',
    name: 'Rouen',
    region: 'northern',
    level: 2,
    population: 15000,
    x: 72,
    y: 12,
    produces: ['coal'],
    needs: ['food', 'fuel', 'medicine'],
    industries: [],
    consumePerDay: { food: 14, medicine: 1, fuel: 9 },
    storageCap: { food: 140, medicine: 14, fuel: 100, coal: 240 },
    influence: 10,
    securityLevel: 1,
    reputation: 'neutral',
  },
  {
    id: 'lille-st',
    name: 'Lille-St',
    region: 'northern',
    level: 1,
    population: 9000,
    x: 70,
    y: 3,
    produces: ['food'],
    needs: ['medicine', 'fuel'],
    industries: ['agriculture'],
    consumePerDay: { food: 8, medicine: 0.6, fuel: 5 },
    storageCap: { food: 160, medicine: 10, fuel: 70 },
    influence: 6,
    securityLevel: 0,
    reputation: 'suspicious',
  },
  {
    id: 'orleans-sud',
    name: 'Orleans-Sud',
    region: 'southern',
    level: 2,
    population: 18000,
    x: 52,
    y: 48,
    produces: ['food', 'timber'],
    needs: ['fuel', 'medicine'],
    industries: ['agriculture', 'sawmill'],
    consumePerDay: { food: 16, medicine: 1.2, fuel: 10 },
    storageCap: { food: 260, medicine: 16, fuel: 130, timber: 180 },
    influence: 14,
    securityLevel: 1,
    reputation: 'neutral',
  },
  {
    id: 'toulouse-c',
    name: 'Toulouse-C',
    region: 'southern',
    level: 1,
    population: 8000,
    x: 18,
    y: 56,
    produces: ['food'],
    needs: ['fuel', 'medicine'],
    industries: ['agriculture'],
    consumePerDay: { food: 7, medicine: 0.5, fuel: 4 },
    storageCap: { food: 120, medicine: 10, fuel: 60 },
    influence: 5,
    securityLevel: 0,
    reputation: 'suspicious',
  },
  {
    id: 'marseille-n',
    name: 'Marseille-N',
    region: 'northern',
    level: 2,
    population: 20000,
    x: 34,
    y: 16,
    produces: ['coal', 'ore'],
    needs: ['food', 'medicine'],
    industries: [],
    consumePerDay: { food: 18, medicine: 1.3, fuel: 6 },
    storageCap: { food: 160, medicine: 18, fuel: 120, coal: 260, ore: 260 },
    influence: 16,
    securityLevel: 1,
    reputation: 'cooperative',
  },
  {
    id: 'strasbourg-o',
    name: 'Strasbourg-O',
    region: 'eastern',
    level: 2,
    population: 13000,
    x: 80,
    y: 34,
    produces: ['ore', 'timber'],
    needs: ['food', 'fuel', 'medicine'],
    industries: [],
    consumePerDay: { food: 12, medicine: 0.9, fuel: 8 },
    storageCap: { food: 130, medicine: 14, fuel: 100, ore: 240, timber: 200 },
    influence: 9,
    securityLevel: 1,
    reputation: 'neutral',
  },
  {
    id: 'metz-sud',
    name: 'Metz-Sud',
    region: 'eastern',
    level: 3,
    population: 30000,
    x: 58,
    y: 36,
    produces: ['steel', 'food'],
    needs: ['machinery', 'medicine', 'fuel'],
    industries: ['steel-mill'],
    consumePerDay: { food: 26, medicine: 1.9, fuel: 15, machinery: 2.5 },
    storageCap: { food: 320, medicine: 30, fuel: 200, steel: 260, ore: 200, coal: 200 },
    influence: 22,
    securityLevel: 2,
    reputation: 'cooperative',
  },
] as CityDef[]

export const SEGMENTS: SegmentDef[] = [
  { id: 'seg-nl-pv', a: 'new-lyon', b: 'paris-valo', km: 210, region: 'central', baseQuality: 0.8 },
  { id: 'seg-pv-ro', a: 'paris-valo', b: 'rouen', km: 95, region: 'central', baseQuality: 0.7 },
  { id: 'seg-ro-li', a: 'rouen', b: 'lille-st', km: 70, region: 'northern', baseQuality: 0.6 },
  { id: 'seg-nl-ma', a: 'new-lyon', b: 'marseille-n', km: 88, region: 'northern', baseQuality: 0.65 },
  { id: 'seg-nl-or', a: 'new-lyon', b: 'orleans-sud', km: 120, region: 'southern', baseQuality: 0.75 },
  { id: 'seg-or-to', a: 'orleans-sud', b: 'toulouse-c', km: 110, region: 'southern', baseQuality: 0.6 },
  { id: 'seg-ma-st', a: 'marseille-n', b: 'strasbourg-o', km: 260, region: 'northern', baseQuality: 0.55 },
  { id: 'seg-st-me', a: 'strasbourg-o', b: 'metz-sud', km: 90, region: 'eastern', baseQuality: 0.7 },
  { id: 'seg-me-pv', a: 'metz-sud', b: 'paris-valo', km: 150, region: 'eastern', baseQuality: 0.7 },
  { id: 'seg-bo-to', a: 'bordeaux-est', b: 'toulouse-c', km: 130, region: 'southern', baseQuality: 0.55 },
  { id: 'loop-a', a: 'new-lyon', b: 'bordeaux-est', km: 140, region: 'central', baseQuality: 0.5, loop: true, loopName: 'Western Reaches' },
  { id: 'loop-b', a: 'bordeaux-est', b: 'toulouse-c', km: 90, region: 'southern', baseQuality: 0.5, loop: true, loopName: 'Southern Spur' },
  { id: 'loop-c', a: 'toulouse-c', b: 'orleans-sud', km: 85, region: 'southern', baseQuality: 0.5, loop: true, loopName: 'Southern Corridor' },
  { id: 'loop-d', a: 'orleans-sud', b: 'metz-sud', km: 200, region: 'eastern', baseQuality: 0.5, loop: true, loopName: 'Eastern Corridor' },
  { id: 'loop-e', a: 'metz-sud', b: 'paris-valo', km: 150, region: 'eastern', baseQuality: 0.5, loop: true, loopName: 'Northern Corridor' },
  { id: 'loop-f', a: 'paris-valo', b: 'new-lyon', km: 210, region: 'central', baseQuality: 0.5, loop: true, loopName: 'Central Link' },
] as SegmentDef[]

export const WORLD: WorldConfig = { cities: CITIES, segments: SEGMENTS, regions: Object.values(REGIONS) }

export const CITY_BY_ID: Record<string, CityDef> = Object.fromEntries(CITIES.map((c) => [c.id, c]))

export const SEGMENT_BY_ID: Record<string, SegmentDef> = Object.fromEntries(SEGMENTS.map((s) => [s.id, s]))

export const LOOP_SEGMENT_IDS = SEGMENTS.filter((s) => s.loop).map((s) => s.id)